### PR TITLE
Added tip for dronekit install

### PR DESCRIPTION
**Pull request by djnugent**
Just a tip for installing dronekit.

### CODE REVIEW

**Comment by hamishwillee** [comment]
The following section installs pip as just another component: 
```
sudo apt-get install python-pip python-numpy python-opencv python-serial python-pyparsing python-wxgtk2.8
```
To my mind adding this tip rather than just installing "all dependencies in one" makes things more complicated. 

Can you explain the benefit. Otherwise recommend reject.

**Comment by djnugent** [comment]
Ah I did not see that. This was more in regards to Mac osx. In my experience I had to install pip before I could do anything. It just depends on how much we want to hold the user's hand through the installation.

**Comment by hamishwillee** [comment]
If it is MacOS relevant then it belongs in the OSX section, not up the top. I haven't tested the existing OSX docs. Again though, with docs we try to keep it simple - so if the step isn't needed, lets not have it.

**Comment by djnugent** [comment]
Alright sounds good

**Comment by hamishwillee** [comment]
Thanks for posting it though - always good to reconsider why we've done things a certain way (often the situation changes too!)

**Pull request closed without merging**
