### PR TITLE
Fixed the error "AttributeError: 'MPStatus' object has no attribute

### PR DESCRIPTION
**Pull request by jmacgithu**
'target_system'" when trying to send a mavlink message.

### CODE REVIEW

**Comment by mrpollo** [comment]
Can you please give us steps to reproduce your problem?, I think a stack trace and list of installed packages would do, just like #30

**Comment by jmacgithu** [comment]
Right now I can't as I've already fixed the dronekit api I'm using. However it happened after I upgraded MAVProxy to 1.4.13 (the latest version as I write) when I needed to send a MAV message via the message_factory method.
The code in MAVProxy/mavproxy.py has changed (classes MPStatus & MPState) and now target_system & target_component are no more available from self.mpstate.status but they can be accessed from self.mpstate.settings.
You can have a look here: https://github.com/tridge/MAVProxy/commit/723eec5b133243758dd8757664d81ccf74dea60e#diff-2da3cf671c984b488ffffdd674c8e0cf
mavproxy.py changed on Feb. 28
My packages are:
droneapi 1.0.3
mavproxy 1.4.13
pymavlink 1.1.51

**Comment by mrpollo** [comment]
thanks thats exactly what i was looking for, reviewing now

**Comment by mrpollo** [comment]
:+1: thanks man

**Pull request merged**
