### PR TITLE
Added Rangefinder class

### PR DESCRIPTION
**Pull request by jmacgithu**

### CODE REVIEW

**Comment by mrpollo** [comment]
@jmacgithu Thanks for the contribution, can you add a description to this PR with what this is and how to use this? ( I some of this on autodocs, but a description on the PR is good for archive )

@djnugent can you please test this

@hamishwillee can you check the docs on this please?

**Comment by jmacgithu** [comment]
I have extended the dronekit apis in order to listen and parse also RANGEFINDER MAVLink messages so that it is possible to extract the distance and voltage values read by the main rangefinder. The distance is rounded up to 2 decimals.
I have tested it on the SITL and with a Iris+ with companion computer.

**Comment by djnugent** [comment]
@mrpollo +1

**Comment by mrpollo** [comment]
thanks @jmacgithu @djnugent

**Comment by hamishwillee** [comment]
@jmacgithu are the units metres and volts?

**Comment by hamishwillee** [comment]
@jmacgithu How did you set up SITL to test this? I have modified the vehicle_state.py example to display the rangefinder data and both voltage/distance report None (which I would assume is correct if no rangefinder is configured by default). I tried setting a sonar in Mission Planner (APM-MAxbotixI2C) - do I need to somehow reboot the system for this to be detected? Anything else?

**Comment by jmacgithu** [comment]
Hi @hamishwillee, I believe I followed these steps http://dev.ardupilot.com/wiki/simulation-2/sitl-simulator-software-in-the-loop/using-sitl-for-ardupilot-testing/#adding_a_virtual_rangefinder
But I insert those commands before implementing the code. When I started implementing it, the rangefinder messages were already flowing in... So that might have helped, or not :smile: 
Then if you add vehicle.add_attribute_observer('rangefinder', rangefinder_callback), you should be able to read the distance with vehicle.rangefinder.distance in the callback.
You should be able to test it also with:
module load graph (when starting mavproxy)
graph RANGEFINDER.distance (once the sitls is running)

**Comment by hamishwillee** [comment]
@jmacgithu Awesome. Thanks. Works well. I'll tidy the docs today.

**Comment by hamishwillee** [comment]
FYI Docs issues addressed by #184

**Pull request merged**
