### PR TITLE
Adds goto test.

### PR DESCRIPTION
**Pull request by tcr3dr**
Copied from vehicle_goto

Issue: timeout added to delay. I think this is because of requirements waiting

Also: rebased over #197

### CODE REVIEW

**Comment by tcr3dr** [comment]
The test here is pretty grim. On a significantly slow platform (free tier of Appveyor) we inadvertently expose the lack of resilience of DKPY code: https://ci.appveyor.com/project/3drobotics/dronekit-python/build/1.0.116

```
link 1 OK
heartbeat OK
GUIDED> Mode GUIDED
APM: Initialising APM...
Got MAVLink msg: COMMAND_ACK {command : 400, result : 0}
 Waiting for arming 36 seconds...
GPS fix lost
 ublox GPS OK
ARMED
APM: DISARMING MOTORS
DISARMED
 Waiting for arming 35 seconds...
 Waiting for arming 34 seconds...
 Waiting for arming 33 seconds...
 Waiting for arming 32 seconds...
 Waiting for arming 31 seconds...
 Waiting for arming 30 seconds...
 Waiting for arming 29 seconds...
 Waiting for arming 28 seconds...
 Waiting for arming 27 seconds...
 Waiting for arming 26 seconds...
 Waiting for arming 25 seconds...
 Waiting for arming 24 seconds...
 Waiting for arming 23 seconds...
```

Arming and immediately disarming the motors can get us into an infinite loop without additional safeguards. I'm concerned these sort of examples are all over the codebase. I'll be adding log dumping to the CI builds so I can see what is triggering this particular issue.

**Comment by mrpollo** [comment]
yes logs should be there, great way to tell what happened, and as a plus since you are running mavproxy you can also get jpegs of plots if you wanted to say debug a failure by plotting

**Comment by hamishwillee** [comment]
@tcr3dr 
>Arming and immediately disarming the motors can get us into an infinite loop without additional safeguards. I'm concerned these sort of examples are all over the codebase.

Are you proposing that the vehicle_goto.py example needs to change? If so, how? I'm not a fan of timeouts - but I was hoping to do additional checks when #156 is merged. 

Taking off in this example can similarly can get "stuck" if for any reason the vehicle is unable to rise (it is possible to have SITL in such a state where this can happen).

**Comment by tcr3dr** [comment]
@hamishwillee No proposal to change the example should come from this. Just pointing out a pedantic issue exposed by the test setup that should be addressed in a general way.

I don't expect to test the examples as-is before additional modifications like #156. These tests should remain separate (hopefully supersets) of the code we recommend.

**Comment by tcr3dr** [comment]
The changes made to SITL to add higher affinity on Windows and also use simulation speedups now result in success ~80% of the time on Windows. Since tests can always be re-run, and nothing will be merged into master if it is not green, I think this is as good as it will get for the moment.

**Comment by tcr3dr** [comment]
Update: I'm going to make this test slightly more general. Hold off on merging.

**Comment by tcr3dr** [comment]
@mrpollo This is good to review again. Made more general and avoids random Appveyor failures with a tunable retry parameter.

**Comment by mrpollo** [comment]
lgtm :+1:

**Pull request merged**
