### PR TITLE
Created windows installer. Use batch file to run it

### PR DESCRIPTION
**Pull request by stephendade**
Installer details
===============

> Added by HamishW - from Stephen email

1. The installer looks for the MAVProxy directory and installs the contents of the ./droneapi and ./examples directories into there.
1. Then simply use the "module load droneapi.module.api" to load it in MAVProxy. (#HW note, it does use the init script too!)
1. The examples can be loaded by the usual "api start ./examples/folder/script"
1. A minimum of MAVProxy 1.4.20 is required to run DroneAPI

Using Installer script
=================

Preconditions
* Install [Inno Setup](http://www.jrsoftware.org/isinfo.php) installed at default location. 
* The script assumes Python is installed in C:\Python27

Build the installation file using \dronekit-python\windows>droneapiWinBuild.bat

The script gets the version number from dronekit's setup.py (It assumes there is a line like ``# version = "12344"``)

### CODE REVIEW

**Comment by hamishwillee** [comment]
@stephendade Are you saying this is an installer that will bundle DroneKit and MAVProxy? If so, you are officially awesome!

**Comment by stephendade** [comment]
Yep :)

Although MAVProxy will need to be installed separately using it's own installer.

**Comment by stephendade** [comment]
I've kept MAVProxy and droneAPI separate in order to make the version control easier.

**Comment by hamishwillee** [comment]
@stephendade We are not worthy. Thank you!

**Comment by hamishwillee** [comment]
@mrpollo Please merge this in :-)

**Comment by hamishwillee** [comment]
@mrpollo I've tested this using a test file Stephen provided and also one I built using the instructions (now added as description). It works well!

The installer script fetches the build number from setup.py to create the build number. We need to set up the toolchain to build this automatically every time we make a new release. 

We also need to decide where/how to host this. It would be good if we could have on a server somewhere with a symlink for "latest" version ([like mavproxy does here](http://firmware.diydrones.com/Tools/MAVProxy/) ). Thoughts.

Anyway, would be excellent if you could merge this in. Many thanks to you @stephendade

**Comment by mrpollo** [comment]
first of thanks to @stephendade for going the extra mile and providing a great PR with clear instructions and readable code.

@stephendade can you please change the wording on any user facing copy from **DroneApi** to **DroneKit**?, I think there are at least 2 labels that I can see from reading the code, not sure if when executing more come up.

second, @hamishwillee this brings some related tasks into consideration:

- Windows versioning and distribution
- Guide changes on windows for installation
- CI/CD builds for Windows on each release http://www.appveyor.com/
- Using DroneKit vs / Working on DroneKit distinction in guides for Windows
- Recommend the MAVProxy installer vs the pip package on Windows, with a note for devs that explains why.

I'm merging this PR as soon as @stephendade can help us by fixing the wording to match our **Marketing** :office:

@hamishwillee can you create new issues from our list above we can go in depth about them there, and also create a milestone for the next release of DroneKit, we will do a new release as soon as those are in and anything else that we can get in between.

Again, outstanding work @stephendade :bowtie:

**Comment by djnugent** [comment]
@stephendade Great work! However, my experience was not perfect. I get this error when I try to import droneapi:
capture2

**Comment by hamishwillee** [comment]
@mrpollo I've created #163 and #164 to track the docs and integration  work (respectively). 

I don't know how to create milestones, or what our process/policy is for doing so. So I am leaving that to you!

**Comment by hamishwillee** [comment]
@stephendade Does the MAVProxy installer clean/replace Windows MAVProxy init file every time it is installed? (%HOMEPATH%\AppData\Local\MAVProxy\mavinit.scr) ?

**Comment by stephendade** [comment]
@hamishwillee  - yes it does replace the file each time

**Comment by stephendade** [comment]
@mrpollo - naming fixed!

**Comment by mrpollo** [comment]
@stephendade thanks!

**Comment by hamishwillee** [comment]
@stephendade Thoughts? Protobuf is listed as a droneapi dependency in pip.

**Comment by stephendade** [comment]
@hamishwillee I'm travelling at the moment, but I should have a chance to look into it sometime this week.

**Comment by hamishwillee** [comment]
@stephendade Thanks very much. I was away last week too.

**Pull request merged**
