### PR TITLE
Merges #217.

### PR DESCRIPTION
**Pull request by tcr3dr**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@tcr3dr Would this fix #121 (don't think so, but just checking!)

**Comment by tcr3dr** [comment]
@hamishwillee Hopefully for Windows at least!

**Comment by tcr3dr** [comment]
WIP, the SITL tests need to be changed to use the MAVProxy.exe file.

**Comment by tcr3dr** [comment]
Closed in favor of #236.

**Pull request closed without merging**
