### PR TITLE
Add main battery support

### PR DESCRIPTION
**Pull request by maruina**
This adds the support for the main battery.
I created a Battery object with voltage, current and level attributes and you can create an observer to update the values.

### CODE REVIEW

**Comment by mrpollo** [comment]
@maruina thanks for your great contribution :+1: this will go in the next release

**Comment by mrpollo** [comment]
@hamishwillee I believe the codeblock should be sufficient for docs but you might want to take a look at it

**Comment by hamishwillee** [comment]
@mrpollo - I can't tell - http://python.dronekit.io/automodule.html has reverted to a very old version (again).
Probably there will be more work to be done in the guide - I've created #137 to track that.

**Comment by mrpollo** [comment]
I just updated the docs so you can see them :)

**Comment by hamishwillee** [comment]
@mrpollo thanks very much. I'll need to doc the member in Vehicle class (missing). #137 has been updated with actions. I'll try to get to that today or Monday.

@maruina Nicely done. Thank you.

**Comment by hamishwillee** [comment]
@mrpollo @maruina there is one slight inconsistency in the implementation. The Battery class returns -1 value when  current measuring (for example) is not implemented. The rest of the API tends to return None for items that "don't work".  @mrpollo - up to you to decide whether this really is an inconsistency, and if so, whether/priority on fixing.

**Comment by maruina** [comment]
Thank you, it's a great project.
@hamishwillee I can fix the code returning None if you prefer that way, no problem.

**Comment by hamishwillee** [comment]
@maruina @mrpollo I would prefer None return for consistency. However @mrpollo is the architect, so final say on him!

**Comment by hamishwillee** [comment]
@maruina , please do change this to return None rather than -1. Also please see bug I reported at the end of #137 . When you've updated your material, I'll rebase and update my patch.

**Pull request merged**
