### PR TITLE
Improve copter simple_goto and adds guide and reference for takeoff

### PR DESCRIPTION
**Pull request by hamishwillee**
The previous simple_goto example had a number of problems, including using channel_override for thrust rather than the takeoff command, lack of pre-arm checks. The update does it the right way. I updated the example documentation along with this.

In addition, I created a guide topic for taking off (copter only) and added apireference for the takeoff function (note, this is just in "text" and I still think we need to expose the method in the API properly).

### CODE REVIEW

**Comment by mrpollo** [comment]
hey @hamishwillee didn't we remove the examples under /example on a previous PR?, aside from that I am about to merge (but will wait until you reply)

**Comment by mrpollo** [comment]
also you might need to rebase with the latest changes from master again, sorry for this :)

**Comment by hamishwillee** [comment]
@mrpollo No worries, all done. 

>didn't we remove the examples under /example on a previous PR?

No, we removed the legacy example docs under /example/documentation. In previous PR we also changed small_demo.py to vehicle_state.py.

**Comment by mrpollo** [comment]
ok cool, what do you think of renaming ```example``` to ```examples```?, it's one of those things that make me cringe when I see it, maybe it's just my OCD

**Comment by hamishwillee** [comment]
> ok cool, what do you think of renaming example to examples?

I must have OCD too. Only concern is that there are a lot of mentions of this now. I'll sort it out though.

**Pull request merged**
