### PR TITLE
Example set position target local ned

### PR DESCRIPTION
**Pull request by jmacgithu**
I've added a new example, which uses the guided mode and set_position_target_local_ned.
I think it's useful in case someone wants to experiment with companion computers.

### CODE REVIEW

**Comment by mrpollo** [comment]
@hamishwillee can you help us review this please.

thanks @jmacgithu.

**Comment by hamishwillee** [comment]
Nice example - thanks. At some point we'll need to plumb it into the proper documentation set.

So I have tested this 




GUIDED> Arming and taking off
Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}
STABILIZE> Mode STABILIZE
timeout setting ARMING_CHECK to 0.000000
Setting GUIDED mode
APM: ARMING MOTORS
Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}
Got MAVLink msg: COMMAND_ACK {command : 400, result : 0}
GUIDED> Mode GUIDED
APM: Initialising APM...
Taking off!
Got MAVLink msg: COMMAND_ACK {command : 22, result : 0}
Flight battery 80 percent
Going North
Got MAVLink msg: MISSION_ACK {target_system : 255, target_component : 0, type : 0}
height 20
APM: EKF variance
LAND> Mode LAND
Going East
Got MAVLink msg: MISSION_ACK {target_system : 255, target_component : 0, type : 0}
height 10
APM: DISARMING MOTORS
DISARMED
Going South
Got MAVLink msg: MISSION_ACK {target_system : 255, target_component : 0, type : 0}
Flight battery 70 percent
Going West
Got MAVLink msg: MISSION_ACK {target_system : 255, target_component : 0, type : 0}
Completed
APIThread-1 exiting...

**Comment by jmacgithu** [comment]
Hi,
I have improved the code and documentation according to the suggestions.

**Comment by hamishwillee** [comment]
Thanks - I think the clarifications are useful. In some places the English is a little clunky - what is the best way for me to "tidy" it - submit a patch after this is approved?

**Comment by jmacgithu** [comment]
Yeah no problem! I'm not a native English speaker, I'm sure few mistakes went through...

**Comment by hamishwillee** [comment]
Cool. @mrpollo - release this and I'll do an update to version in master shortly after.

**Comment by mrpollo** [comment]
Sure thing, @jmacgithu can you first squash some of the latest commits? at least the 3 last "Improved documentation" commits. Let me know if you need help squashing the commits

**Comment by jmacgithu** [comment]
It should be ok now

**Comment by mrpollo** [comment]
:+1:

**Pull request merged**
