### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by tcr3dr**

### CODE REVIEW

**Comment by mrpollo** [comment]
```github_latest_release.txt``` ?

**Comment by tcr3dr** [comment]
@mrpollo Added.

**Comment by mrpollo** [comment]
awesome, good to merge then?

**Comment by hamishwillee** [comment]
@tcr3dr @mrpollo YOu know that this isn't how it is supposed to work right?

What is supposed to happen is that you create the release notes here. Then run https://github.com/diydrones/dronekit-python/blob/master/docs/get_release_notes.py and that will create github_latest_release.txt for you.

**Comment by tcr3dr** [comment]
@hamishwillee Ah, I did run that script. That was was generated from the Release Notes page.

**Comment by tcr3dr** [comment]
However, I would agree that the release notes PR should be separate from the release push? Since I inadvertantly played some git trickery here.

**Comment by hamishwillee** [comment]
Yes, you did everything correct. I mistook this for the release notes page. Sorry!

**Pull request merged**
